#!/bin/bash
echo "=== Testing All API Endpoints ==="
echo ""
echo "1. Overview:"
curl -s http://localhost:8000/api/overview | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'  Metrics: {d.get(\"metrics\", {})}'); print(f'  Status dist: {len(d.get(\"status_distribution\", {}))}'); print(f'  Critical: {len(d.get(\"critical_stockout\", []))}'); print(f'  Top stock: {len(d.get(\"top_stock\", []))}'); print(f'  Top risks: {len(d.get(\"top_risks\", []))}'); print(f'  Recent purchases: {len(d.get(\"recent_purchases\", []))}'); print(f'  Recent usage: {len(d.get(\"recent_usage\", []))}')"
echo ""
echo "2. Inventory:"
curl -s http://localhost:8000/api/inventory | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'  Items: {len(d.get(\"data\", []))}')"
echo ""
echo "3. Risk Alerts:"
curl -s http://localhost:8000/api/risk-alerts | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'  Alerts: {len(d.get(\"data\", []))}'); print(f'  Summary: {d.get(\"summary\", {})}')"
echo ""
echo "4. Usage Trends:"
curl -s http://localhost:8000/api/usage-trends | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'  Trends: {len(d.get(\"trends\", []))}'); print(f'  Top ingredients: {len(d.get(\"top_ingredients\", []))}')"
echo ""
echo "5. Shipments:"
curl -s http://localhost:8000/api/shipments | python3 -c "import sys, json; d=json.load(sys.stdin); print(f'  Delay analysis: {len(d.get(\"delay_analysis\", []))}'); print(f'  Supplier reliability: {len(d.get(\"supplier_reliability\", []))}'); print(f'  Shipments: {len(d.get(\"shipments\", []))}')"
